# Generated by Django 5.0.1 on 2024-02-02 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('signature', models.CharField(default='Your Name', max_length=140)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
